### PR TITLE
Email verification

### PR DESCRIPTION
**Pull request by Habeebllah**

### CODE REVIEW

**Comment by Habeebllah** [comment]
user model updated, kindly makemigrations and migrate

**Comment by Habeebllah** [comment]
Also, new library installed. run pip install requirements.txt to install new libraries

**Review by RydahApp — COMMENTED** [review]
can you make the view page slim as possible , i rather all the logic in serializer

**Review by RydahApp — APPROVED** [review]
i'm gonna to approve but can you re arrange coding as i wan the view to be as slim

**Pull request merged**
